---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - yarn remove node-sass
  - npm install bower
  - npm install phantomjs-prebuilt
  - yarn add node-sass

install:
  - npm install
  - bower install

script:
  - npm test
